--- 
pid: tmp/pids/thin.pid
log: log/thin.log
port: 5000
max_conns: 1024
timeout: 30
chdir: /Users/mfosse/dev/railscasts
max_persistent_conns: 512
environment: production
address: 0.0.0.0
servers: 3
daemonize: true
